# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/4c34d7091f483ba25a2817c5eb83faa59a842300/.rubocop.yml
AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
Naming/HeredocDelimiterNaming:
  Exclude:
    - "spec/**/*"
Naming/MethodName:
  Exclude:
    - "lib/hanami/utils/kernel.rb"
Layout/HashAlignment:
  Enabled: false
Style/CommentedKeyword:
  Exclude:
    - "spec/**/*"
Style/DateTime:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - "spec/**/*"
Style/MethodMissingSuper:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/RescueStandardError:
  Exclude:
    - "spec/**/*"
