# Please keep AllCops, Bundler, Style, Metrics groups and then order cops
# alphabetically
inherit_from:
  - https://raw.githubusercontent.com/hanami/devtools/120088ec992c536a63e37ec42aaf0f0b1adb33a8/.rubocop.yml
AllCops:
  Exclude:
    - "tmp/**/*"
    - "vendor/**/*"
Naming/HeredocDelimiterNaming:
  Exclude:
    - "spec/**/*"
Naming/MethodName:
  Exclude:
    - "lib/hanami/utils/kernel.rb"
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Exclude:
    - "lib/hanami/utils/escape.rb"
    - "spec/**/*"
Style/CommentedKeyword:
  Exclude:
    - "spec/**/*"
Style/DateTime:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/FormatStringToken:
  Exclude:
    - "spec/**/*"
Style/MethodMissingSuper:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
Style/RescueStandardError:
  Exclude:
    - "spec/**/*"
