#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

setup() {
  bundle install --retry=10 --jobs=$(_cpu_count)
}

qa() {
  rubocop_check
}

specs() {
  run_unit_tests &&
    run_isolation_tests
}

rubocop_check() {
  bundle exec rubocop --parallel
}

_cpu_count() {
    if [ -z "$(command -v sysctl)" ]; then
      echo $(sysctl -n hw.cpu)
    elif [ -f /proc/cpuinfo ]; then
      echo $(grep -c ^processor /proc/cpuinfo)
    else
      echo 1
    fi
}

run_unit_tests() {
  bundle exec rake spec:coverage
}

run_isolation_tests() {
  local pwd=$PWD
  local root="$pwd/spec/isolation"

  for test in $(find $root -name '*_spec.rb')
  do
    run_isolation_test $test

    if [ $? -ne 0 ]; then
      local exit_code=$?
      echo "Failing test: $test"
      exit $exit_code
    fi
  done
}

run_isolation_test() {
  local test=$1

  printf "\n\n\nRunning: $test\n"
  ruby $test --options spec/isolation/.rspec
}

run_test() {
  local test=$1

  printf "\n\n\nRunning: $test\n"
  COVERAGE=true bundle exec rspec $test
}

main() {
  local subcommand=$@
  setup

  if [ "$subcommand" = "qa" ]; then
    qa
  else
    specs
  fi
}

main $@
